apiVersion: v1
kind: Service
metadata:
  name: sample-microservice
  labels:
    app: sample-microservice
spec:
  type: NodePort
  selector:
    app: sample-microservice
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000